### ISSUE TITLE
README recommends not installing it directly to projects

### ISSUE THREAD

**Issue by guillempuche** [powersync-ja/react-native-quick-sqlite#46]
`@powersync/react-native` recommends installing this package https://github.com/powersync-ja/powersync-js/tree/main/packages/react-native#install-peer-dependency-sqlite

Which guide do we follow?

**Comment by stevensJourney** [comment]
I believe the intention of the message on this package's readme is for developers not to use this package if not using the PowerSync SDK.

This fork contains PowerSync specific SQLite extension functionality. 

I can see how the wording might be confusing. Currently this package is a peer dependency of `@powersync/react-native`. In some circumstances peer dependencies are automatically installed, in which case there is no need to directly install this package. 

We can improve the message on this readme.

**Comment by guillempuche** [comment]
Then our reps need to install it to be sure?

**Comment by stevensJourney** [comment]
> Then our repos need to install it to be sure?

You will quickly notice if this package is not installed. It's only necessary to explicitly install this package if your project has explicitly disabled installation of peer dependencies.

**Comment by rkistner** [comment]
Fixed in #50.
